name: cancel-deployment
run-name: '[CD] Canceled deployment of the website by @${{ github.actor }}'

on:
    workflow_run:
        branches: [main]
        types: [requested]
        workflows: [continuous-deployment]

jobs:
    canceled-deployment-website:
        name: '[CD] Canceled deployment of the website'
        runs-on: ubuntu-latest
        steps:
            -
                name: '[GITHUB / OFFICIAL] Checkout'
                uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
            -
                name: '[OSS] Verify changed files'
                uses: tj-actions/verify-changed-files@a148bdba9d2477a2aca3537bd6bc7a7af54b06f2 # v13.0.0
                id: verify-changed-files
                with:
                    files: |
                        example
                        src
                        index.html
            -
                name: '[OSS] Canceled deployment if no files are modified'
                if: steps.verify-changed-files.outputs.files_changed != 'true'
                uses: styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5 # v0.11.0
                with:
                    access_token: ${{ github.token }}
                    ignore_sha: true
                    workflow_id: ${{ github.event.workflow.id }}
