name: 'ContinuousIntegration'

on:
    push:
        branches: [master]
    pull_request:
        # The branches below must be a subset of the branches above
        branches: [master]

jobs:
    commitlint:
        name: 'Commit lint'
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout'
              uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
              with:
                  fetch-depth: 0
            - name: 'Launch commitlint'
              uses: wagoid/commitlint-github-action@481aff4de4d0de6d28d05533d4230d298ea3377d # v5.3.0
              with:
                  configFile: '.commitlintrc.json'
    tests:
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                node_version:
                    - 14
                    - 16
                    - 17
                architecture:
                    - x64
        name: 'Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}'
        runs-on: ${{ matrix.os }}
        steps:
            - name: 'Checkout'
              uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
            - name: 'Setup node'
              uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
              with:
                  node-version: ${{ matrix.node_version }}
                  architecture: ${{ matrix.architecture }}
            - name: 'Setup PNPM'
              uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # v2.2.4
              with:
                  version: 6.10.0
            - name: 'Install project'
              run: pnpm install
            - name: '[For UbuntuOS] Install xvfb'
              if: matrix.os == 'ubuntu-latest'
              run: sudo apt-get install xvfb
            - name: 'Launch build'
              run: pnpm run build
            - name: 'Launch linter'
              run: pnpm run lint
            - name: '[For UbuntuOS] Launch test'
              if: matrix.os == 'ubuntu-latest'
              run: xvfb-run --auto-servernum pnpm run test
            - name: '[For MacOS] Launch test'
              if: matrix.os == 'macos-latest'
              run: pnpm run test
