name: Continuous Integration

on:
    pull_request:
    push:

jobs:
    commitlint:
        name: 'Commit lint'
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout'
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: 'Launch commitlint'
              uses: wagoid/commitlint-github-action@v4
              with:
                  configFile: '.commitlintrc.json'
    tests:
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                node_version:
                    - 14
                    - 16
                    - 17
                architecture:
                    - x64
        name: 'Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}'
        runs-on: ${{ matrix.os }}
        steps:
            - name: 'Checkout'
              uses: actions/checkout@v2
            - name: 'Setup node'
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node_version }}
                  architecture: ${{ matrix.architecture }}
            - name: 'Setup PNPM'
              uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
              with:
                  version: 6.10.0
            - name: 'Install project'
              run: pnpm install
            - name: '[For UbuntuOS] Install xvfb'
              if: matrix.os == 'ubuntu-latest'
              run: sudo apt-get install xvfb
            - name: 'Launch build'
              run: pnpm build
            - name: 'Launch linter'
              run: pnpm run lint
            - name: '[For UbuntuOS] Launch test'
              if: matrix.os == 'ubuntu-latest'
              run: xvfb-run --auto-servernum pnpm test
            - name: '[For MacOS] Launch test'
              if: matrix.os == 'macos-latest'
              run: pnpm test
