name: snyk-infrastructure-analysis
run-name: '[SNYK] ${{ github.event.head_commit.message }}'

on:
    push:
        branches: [master]
    pull_request:
        # The branches below must be a subset of the branches above
        branches: [master]

concurrency:
    group: 'snyk-infrastructure-analysis-${{ github.ref }}'
    cancel-in-progress: true

jobs:
    snyk:
        runs-on: ubuntu-latest
        environment: 'Continous Integration'
        steps:
            -
                name: '[GITHUB / OFFICIAL] Checkout'
                uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
            -
                name: '[INTERNAL] Install project & environment'
                uses: ./.github/actions/install
                with:
                    architecture: x64
                    node-version: 18
            -
                name: 'Launch build'
                shell: sh
                run: pnpm run build
            -
                name: 'Run Snyk to check for vulnerabilities'
                uses: snyk/actions/node@master
                continue-on-error: true
                env:
                    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
                with:
                    args: --severity-threshold=high --sarif-file-output=snyk.sarif
            -
                name: Upload result to GitHub Code Scanning
                uses: github/codeql-action/upload-sarif@v1
                with:
                    category: snyk-tool
                    sarif_file: snyk.sarif
